version: '3.7'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: httpd
    volumes:
      - /home/ec2-user/silver/:/home/silver
    ports:
      - "80:80"
    privileged: true
